import { type NextPage } from "next";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";
import {FaRegPlusSquare, FaChartBar, FaUser, FaSignOutAlt} from "react-icons/fa"
import Link from "next/link";
import { CircularProgress } from "@mui/material";
import { Menu } from "@headlessui/react";
import Image from "next/image";

const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <Navbar />
      </main>
    </>
  );
};

export default Home;

const Navbar: React.FC = () => { 
  const { data: sessionData } = useSession();


  const UserMenu = () => {
    if(!sessionData) return <CircularProgress />;

    return (
      <Menu>
        <Menu.Button>
          <Image className="rounded-full" width={30} height={30} src={sessionData.user.image as string} alt={`${sessionData.user.name as string}'s profile picture`}></Image>
        </Menu.Button>
        <Menu.Items className="absolute flex flex-col mt-32 shadow-md rounded">
          <button>
            <div className="flex flex-row items-center gap-2 p-2">
              <FaUser />
              <p>Account</p>
            </div>
          </button>
          <button onClick={() => void signOut()}>
            <div className="flex flex-row items-center gap-2 p-2">
              <FaSignOutAlt />
              <p>Sign out</p>
            </div>
          </button>
        </Menu.Items>
      </Menu>
    )
  }

  const UserOptions = () => {
    return (
      <div className="flex flex-row items-center gap-6">
        <button>
          <FaRegPlusSquare />
        </button>
        <Link href={"/stats"}>
          <FaChartBar />
        </Link>
        <UserMenu />
      </div>
    )
  }

  return (
    <div className="flex flex-row justify-between h-16 items-center px-4">
      <div className="font-bold">
        trakr.
      </div>
      {sessionData ? <UserOptions /> : <button onClick={() => void signIn()}>Sign in</button>}
    </div>
  )
};

