import { type NextPage } from "next";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";
import {FaRegPlusSquare, FaChartBar} from "react-icons/fa"
import Link from "next/link";
import { Menu } from "@headlessui/react";
import { api } from "~/utils/api";

const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <Navbar />
        <AuthShowcase />
      </main>
    </>
  );
};

export default Home;

const Navbar: React.FC = () => { 

  return (
    <div className="flex flex-row justify-between">
      <div className="font-bold">
        trakr.
      </div>
      <div className="flex flex-row items-center gap-4">
        <button>
          <FaRegPlusSquare />
        </button>
        <Link href={"/stats"}>
          <FaChartBar />
        </Link>
      </div>
    </div>
  )
};

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold no-underline transition hover:bg-white/20"
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
};
